name: objectscriptquality
on: push

jobs:
  linux:
    name: Linux build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Execute ObjectScript Quality Analysis
      env:
        JENKINS_OBJECTSCRIPTQUALITY_USER: hook
        JENKINS_OBJECTSCRIPTQUALITY_PASSWORD: ${{ secrets.jenkinsPass }}
        JENKINS_OBJECTSCRIPTQUALITY_TRIGGER_ACCESS_TOKEN: ${{ secrets.jobToken }}
      run: wget https://raw.githubusercontent.com/asamo7/jenkins-objectscriptquality-integration/master/hook.sh && sh ./hook.sh
